# -*- coding: utf-8 -*-
"""analisis_flashweave_20251113_sab_paragithub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GO1YDq2MUOS36M3nVL2sMhp6X6_SHAN2
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import networkx as nx

from networkx.readwrite import json_graph
import json

import pandas

import copy
import random
import csv

import seaborn as sns

MUNO_mv = nx.read_gml("muno_mv.gml")
MUNO = nx.read_gml("muno.gml")

MUO_mv = nx.read_gml("muo_mv.gml")
MUO = nx.read_gml("muo.gml")

def build_degree_df(networks):
    frames = []

    for name, G in networks.items():
        degrees = dict(G.degree())
        mv_values = nx.get_node_attributes(G, "mv")
        df = pd.DataFrame({
            "node": list(degrees.keys()),
            "degree": list(degrees.values()),
            "mv": [mv_values.get(n, 0) for n in degrees.keys()],
            "network": name
        })
        frames.append(df)

    return pd.concat(frames, ignore_index=True)

networks = {
    "MUNO": MUNO_mv,
    "MUO": MUO_mv
}

df_deg = build_degree_df(networks)

for net in (MUNO_mv, MUO_mv):
  print(net.order(), net.size())

for net in (MUNO_mv, MUNO, MUO_mv, MUO):
  print(net.order(), net.size(),
        nx.number_connected_components(net))

df_deg[df_deg["mv"] == 1]

df_deg.groupby(["network", "mv"])["degree"].mean()

def missing_edges(original, filtered):
    orig_edges = set(original.edges())
    filt_edges = set(filtered.edges())

    missing = orig_edges - filt_edges
    return missing

missing_MUNO = missing_edges(MUNO, MUNO_mv)
missing_MUO = missing_edges(MUO, MUO_mv)

print("MUNO missing edges:", len(missing_MUNO))
print("MUO missing edges:", len(missing_MUO))

def plot_missing_edges(ax, original, filtered, title="Network"):

    pos = nx.spring_layout(original, seed = 42)

    missing_edges = set(original.edges()) - set(filtered.edges())
    print(len(missing_edges))

    nx.draw_networkx_nodes(original, pos,  ax=ax,
                           node_size=100,
                           node_color="orange",
                           edgecolors="black",
                           linewidths=1.2,
                           alpha=0.9)

    present_edges = [e for e in original.edges() if e not in missing_edges]
    nx.draw_networkx_edges(original, pos, edgelist=present_edges, edge_color="grey",
                           width=0.5, alpha=0.6, ax=ax)

    nx.draw_networkx_edges(original, pos, edgelist=missing_edges, edge_color="red",
                           width=2, alpha=0.8, ax=ax)

    ax.set_title(title, fontsize=12)
    ax.axis("off")

fig, axes = plt.subplots(1, 2, figsize=(9,6), dpi=300)

plot_missing_edges(axes[0], MUNO, MUNO_mv, "MUNO")
plot_missing_edges(axes[1], MUO, MUO_mv, "MUO")

plt.tight_layout()

plt.savefig("missingEdges.png",
            format='png', dpi=1200,
            bbox_inches='tight')

plt.show()